name: Traefik
version: "3.6.6"
slug: traefik
description: |
  Traefik is a modern HTTP reverse proxy and load balancer that makes deploying
  microservices easy.
arch:
  - aarch64
  - amd64
startup: system
init: false
stage: stable
boot: auto
url: https://github.com/mikeomat/hassio-addons/tree/main/traefik
ports:
  80/tcp: 80
  443/tcp: 443
  8080/tcp: 8080
ports_description:
  80/tcp: HTTP
  443/tcp: HTTPS
  8080/tcp: Web Interface
discovery:
  - traefik
hassio_role: default
hassio_api: true
panel_icon: mdi:earth-arrow-right
map:
  - ssl:rw
  - type: addon_config
    path: /config
options:
  log_level: info
  access_logs: false
  forwarded_headers_insecure: false
  insecure_skip_verify: false
  dynamic_configuration_path: "/config"
  letsencrypt:
    enabled: false
    resolvers: []
  env_vars: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  access_logs: bool
  forwarded_headers_insecure: bool
  insecure_skip_verify: bool
  dynamic_configuration_path: str
  letsencrypt:
    enabled: bool
    email: email?
    challenge_type: match(tlsChallenge|httpChallenge|dnsChallenge)?
    ca_server: str?
    provider: str?
    delayBeforeCheck: int?
    resolvers:
      - str?
  plugins: str?
  env_vars:
    - str
